spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_PROD_DATASOURCE_URL}
    username: ${SPRING_PROD_DATASOURCE_USERNAME}
    password: ${SPRING_PROD_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
frontendUrl: https://chitragupt-frontend.vercel.app
baseUrl: http://chitragupt-production.up.railway.app
