ALTER TABLE users.users
ADD COLUMN IF NOT EXISTS first_name VARCHAR(30) NOT NULL,
ADD COLUMN IF NOT EXISTS middle_name VARCHAR(30),
ADD COLUMN IF NOT EXISTS last_name VARCHAR(30),
ADD COLUMN IF NOT EXISTS contact_number VARCHAR(15);


ALTER TABLE patient.patient
ADD COLUMN IF NOT EXISTS user_id BIGINT NOT NULL UNIQUE;